# ----
# Site

title: pyiron
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:
email: pyiron@mpie.de
formspree: https://formspree.io/xrgywnvn
copyright: Max Planck Institut für Eisenforschung, GmbH - Computational Materials Design (CM) Department. All rights reserved.

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: An interactive development environment (IDE) for computational materials science.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# -----
# Build

timezone: Etc/UTC

# collections:
#   staff_members:
#     _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
