# ----
# Site

title: pyiron
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:
email: pyiron@mpie.de

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: An interactive development environment (IDE) for computational materials science.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name:
  links:

# -----
# Build

timezone: Etc/UTC

collections:
  core_developers:
    _hide_content: true
  collaborators:
    _hide_content: true
  affiliated_projects:
    _hide_content: true

# Members of pyiron's steering committee
steering_committee:
  -
    name: Mira Todorova
    institution: MPIE
  -
    name: Christoph Freysoldt
    institution: MPIE
  -
    name: Tilmann Hickel
    institution: MPIE
  -
    name: Blazej Grabowski
    institution: Uni-Stuttgart
  -
    name: Ralf Drautz
    institution: ICAMS
  -
    name: Thomas Hammerschmidt
    institution: ICAMS

# Previous pyiron developers who are not on Github
alumni:
  -
    name: Ugur Aydin
    contribution: Developer of pyCMW (pyiron predecessor)
    dates: 2011-2015
  - 
    name: Ankit Gupta
    contribution: Kinetic Monte Carlo implementation
    dates: 2014-2015
  -
    name: Murat Celik
    contribution: Sqlalchemy-based database adapter
    dates: 2016-2017
  -
    name: Navid Shayanfar
    contribution: Parser for SPHInX
    dates: 2017
  -
    name: Martin Boeckmann
    contribution: Metropolis Monte Carlo implementation
    dates: 2017-2018
  -
    name: Murali Uddagiri
    contribution: Generation of special quasirandom structures
    dates: 2017-2018
  -
    name: Markus Tautschning
    contribution: Structure optimization with VASP
    dates: 2018-2019

# Github usernames that will be excluded
# from the Team page (see team.html)
github_bots:
  - "pyironlandingpage"
  - "codacy-badger"
  - "IceflowRE"

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "core_developers"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
      type: "collaborators"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
      type: "affiliated_projects"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
